[package]
name = "ffi_macros"
version = "0.2.0"
authors = ["HaoXuan40404 <444649358@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

